### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by sparkuss** [solarlabsteam/cosmos-exporter#4]
Can't start cosmos-explorer, getting an error and program stopped.
Any idea how I can debug this?

```
$ /usr/local/bin/cosmos-exporter --node="127.0.0.11:9090" --tendermint-rpc="http://127.0.0.11:26657" --bech-prefix="rizon" --denom="uatolo"
7:24AM INF Config file not provided
7:24AM INF Started with following parameters --bech-account-prefix=rizon --bech-account-pubkey-prefix=rizonpub --bech-consensus-node-prefix=rizonvalcons --bech-consensus-node-pubkey-prefix=rizonvalconspub --bech-validator-prefix=rizonvaloper --bech-validator-pubkey-prefix=rizonvaloperpub --denom=uatolo --listen-address=:9300 --log-level=info --node=127.0.0.11:9090
7:24AM INF Got network status from Tendermint network=titan-1
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.setDenom(0xc000d82700)
        /home/runner/work/cosmos-exporter/cosmos-exporter/main.go:230 +0x610
main.Execute(0x216f220, 0xc0001b3ec0, 0x0, 0x4)
        /home/runner/work/cosmos-exporter/cosmos-exporter/main.go:162 +0x725
github.com/spf13/cobra.(*Command).execute(0x216f220, 0xc000180060, 0x4, 0x4, 0x216f220, 0xc000180060)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x216f220, 0x217bce0, 0x1527680, 0x21)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        /home/runner/work/cosmos-exporter/cosmos-exporter/main.go:272 +0x5f5
$

```

**Comment by Freak12Techno** [comment]
Hi, can you run `<app binary> query bank denom-metadata` and post the output?
I'm assuming it returns the denoms information in a different way than any other binaries I've tested it on, but I don't have a Rizon fullnode unfortunately so I can't check it by myself.

**Comment by sparkuss** [comment]
starsd query --node "tcp://127.0.0.11:26657" bank denom-metadata
metadatas: []
pagination:
  next_key: null
  total: "0"
---
I will check also my another nodes now, what are they returns

**Comment by Freak12Techno** [comment]
Ummmm lol, it doesn't return any of the denom information and crashes about that. For example, here's what the command does on Sentinel:

```
sentinelhub query bank denom-metadata --node https://rpc.sentinel.co:443
metadatas:
- base: udvpn
  denom_units:
  - aliases: []
    denom: dvpn
    exponent: 6
  - aliases:
    - millidvpn
    denom: mdvpn
    exponent: 3
  - aliases:
    - microdvpn
    denom: udvpn
    exponent: 0
  description: The native staking token of the Sentinel Hub.
  display: dvpn
pagination:
  next_key: null
  total: "1"
```

as you can see, the metadatas is not empty.

You can fix it by running it by specifying `--denom` and `--denom-coefficient` manually, so it won't use the results from the node (something like `--denom atolo --denom-coefficient 1000000`), meanwhile the app should crash if no metatatas, but giving some fancy error in return. I'll fix it and close it after.

Let me know if the approach above would work for you.
